# languages.py
# Owner: Friend
# English / French / Kinyarwanda texts for menus
# other modules call languages.t("key")

current_language = "en"

# big dictionary with 3 languages
TEXTS = {
    "en": {
        "choose_language_title": "CHOOSE LANGUAGE / HITAMO URURIMI / CHOISIR LA LANGUE",
        "lang_option_en": "1. English",
        "lang_option_fr": "2. Francais",
        "lang_option_rw": "3. Ikinyarwanda",
        "lang_prompt": "Enter choice (1-3): ",
        "lang_invalid": "Invalid choice. Using English.",
        "lang_set_en": "Language set to English.",
        "lang_set_fr": "Langue definie: Francais.",
        "lang_set_rw": "Ururimi: Ikinyarwanda.",
        "connecting": "Connecting to MySQL...",
        "setup_help": "Setup help:",
        "setup1": "1. Start MySQL on your computer",
        "setup2": "2. Run: mysql -u root < database.sql",
        "setup3": "3. Put your MySQL password in config.py if needed",
        "app_title": "   UmugandaSync - Community Work Management System",
        "app_subtitle": "   Digital Umuganda for Village / Umudugudu Leaders",
        "please_login": "Please log in to continue.",
        "demo_login": "(Demo: username=admin  password=admin123)",
        "username": "Username: ",
        "password": "Password: ",
        "login_ok": "Login successful. Welcome,",
        "login_bad": "Invalid username or password.",
        "attempts_left": "Attempts left:",
        "too_many_attempts": "Too many failed attempts. Exiting.",
        "entry_title": "WHO IS ENTERING?",
        "entry_admin": "1. Village Leader / Admin (full system)",
        "entry_member": "2. Community Member (my participation only)",
        "entry_exit": "0. Exit",
        "entry_prompt": "Enter choice: ",
        "member_entry_title": "MEMBER ACCESS",
        "member_entry_help": "Enter your Member ID and phone to view your Umuganda record.",
        "member_id_prompt": "Your Member ID: ",
        "member_phone_prompt": "Your phone number: ",
        "member_login_ok": "Welcome,",
        "member_login_bad": "Member ID and phone do not match. Try again.",
        "member_inactive": "Your account is Inactive. Ask the Village Leader for help.",
        "member_menu_title": " MEMBER MENU",
        "member_menu_summary": "1. View my participation summary",
        "member_menu_history": "2. View my attendance history",
        "member_menu_language": "3. Change language",
        "member_menu_logout": "4. Logout / Back to entry",
        "member_menu_exit": "0. Exit",
        "member_demo": "(Demo tip: ID=1 phone=0788000001  or  ID=3 phone=0788000003)",
        "main_menu": " MAIN MENU",
        "menu_members": "1. Member Management",
        "menu_attendance": "2. Attendance",
        "menu_projects": "3. Projects",
        "menu_tools": "4. Tool Inventory",
        "menu_reports": "5. Reports",
        "menu_search": "6. Universal Search",
        "menu_refresh": "7. Refresh Dashboard",
        "menu_language": "8. Change Language",
        "menu_logout": "9. Logout",
        "menu_exit": "0. Exit",
        "enter_choice": "Enter choice: ",
        "invalid_choice": "Invalid choice. Please try again.",
        "refreshing": "Refreshing dashboard...",
        "logged_out": "Logged out.",
        "goodbye": "Goodbye. Thank you for serving the community with UmugandaSync.",
        "press_enter": "\nPress Enter to continue...",
        "empty_input": "Input cannot be empty. Try again.",
        "invalid_number": "Please enter a valid whole number (0 or more).",
        "invalid_range": "Please enter a number between",
        "and": "and",
        "invalid_date": "Invalid date. Example: 2026-07-23",
        "date_prompt": " (YYYY-MM-DD): ",
        "yn_prompt": " (y/n): ",
        "dashboard": "DASHBOARD - ",
        "total_members": "TOTAL MEMBERS      :",
        "active_members": "ACTIVE MEMBERS     :",
        "today_attendance": "TODAY'S ATTENDANCE :",
        "ongoing_projects": "ONGOING PROJECTS   :",
        "available_tools": "AVAILABLE TOOLS    :",
        "low_stock_tools": "LOW STOCK TOOLS    :",
        "overdue_projects": "OVERDUE PROJECTS   :",
        "notifications": "=== NOTIFICATIONS ===",
        "warn_low_stock": "Warning: {n} tool(s) are almost finished / low stock.",
        "warn_overdue": "Warning: Project {name} is overdue.",
        "notice_no_attendance": "Notice: No attendance has been recorded today.",
        "notice_absents": "Notice: {n} member(s) were Absent on {date}.",
        "no_warnings": "No urgent warnings. Community records look okay.",
        "member_menu": "MEMBER MANAGEMENT",
        "m1": "1. Add Member",
        "m2": "2. View All Members",
        "m3": "3. Search Member",
        "m4": "4. Update Member",
        "m5": "5. Delete Member",
        "m6": "6. Deactivate Member",
        "m7": "7. Reactivate Member",
        "m0": "0. Back to Main Menu",
        "attendance_menu": "ATTENDANCE",
        "a1": "1. Record Attendance",
        "a2": "2. View All Attendance",
        "a3": "3. View by Date",
        "a4": "4. View by Member",
        "a5": "5. Search Attendance",
        "a6": "6. Attendance Percentage for Member",
        "a7": "7. Analytics (active / poor / missed 3)",
        "a8": "8. Record attendance for whole village / all members",
        "a9": "9. Member participation summary (lifetime)",
        "a0": "0. Back to Main Menu",
        "project_menu": "PROJECT MANAGEMENT",
        "p1": "1. Register Project",
        "p2": "2. View All Projects",
        "p3": "3. View Ongoing Projects",
        "p4": "4. View Completed Projects",
        "p5": "5. View Overdue Projects",
        "p6": "6. Search Projects",
        "p7": "7. Update Project Progress / Status",
        "p8": "8. Mark Project Completed",
        "p9": "9. Delete Project",
        "p0": "0. Back to Main Menu",
        "tools_menu": "TOOL INVENTORY",
        "t1": "1. Register Tool",
        "t2": "2. View All Tools",
        "t3": "3. Update Tool",
        "t4": "4. Delete Tool",
        "t5": "5. Borrow Tool",
        "t6": "6. Return Tool",
        "t7": "7. Low Stock Warning",
        "t8": "8. View Borrow History",
        "t0": "0. Back to Main Menu",
        "reports_menu": "REPORTS",
        "r1": "1. Community Summary",
        "r2": "2. Member Report",
        "r3": "3. Attendance Summary",
        "r4": "4. Most Active Members",
        "r5": "5. Members with Poor Attendance",
        "r6": "6. Project Summary",
        "r7": "7. Inventory Summary",
        "r8": "8. Attendance by Village",
        "r0": "0. Back to Main Menu",
        "search_menu": "UNIVERSAL SEARCH",
        "s1": "1. Search Member (ID / name / phone)",
        "s2": "2. Search Project by name",
        "s3": "3. Search Tool by name",
        "s4": "4. Search Attendance by date",
        "s0": "0. Back",
        "back": "0. Back to Main Menu",
    },
    "fr": {
        "choose_language_title": "CHOISIR LA LANGUE / HITAMO URURIMI / CHOOSE LANGUAGE",
        "lang_option_en": "1. English",
        "lang_option_fr": "2. Francais",
        "lang_option_rw": "3. Ikinyarwanda",
        "lang_prompt": "Entrez le choix (1-3): ",
        "lang_invalid": "Choix invalide. Anglais utilise.",
        "lang_set_en": "Language set to English.",
        "lang_set_fr": "Langue definie: Francais.",
        "lang_set_rw": "Ururimi: Ikinyarwanda.",
        "connecting": "Connexion a MySQL...",
        "setup_help": "Aide a l'installation:",
        "setup1": "1. Demarrez MySQL sur votre ordinateur",
        "setup2": "2. Executez: mysql -u root < database.sql",
        "setup3": "3. Mettez le mot de passe MySQL dans config.py si besoin",
        "app_title": "   UmugandaSync - Gestion du travail communautaire",
        "app_subtitle": "   Umuganda numerique pour les leaders d'Umudugudu",
        "please_login": "Veuillez vous connecter pour continuer.",
        "demo_login": "(Demo: utilisateur=admin  motdepasse=admin123)",
        "username": "Nom d'utilisateur: ",
        "password": "Mot de passe: ",
        "login_ok": "Connexion reussie. Bienvenue,",
        "login_bad": "Nom d'utilisateur ou mot de passe incorrect.",
        "attempts_left": "Tentatives restantes:",
        "too_many_attempts": "Trop d'echecs. Fermeture.",
        "entry_title": "QUI ENTRE?",
        "entry_admin": "1. Leader / Admin (systeme complet)",
        "entry_member": "2. Membre de la communaute (ma participation seulement)",
        "entry_exit": "0. Quitter",
        "entry_prompt": "Entrez le choix: ",
        "member_entry_title": "ACCES MEMBRE",
        "member_entry_help": "Entrez votre ID membre et telephone pour voir votre dossier Umuganda.",
        "member_id_prompt": "Votre ID membre: ",
        "member_phone_prompt": "Votre numero de telephone: ",
        "member_login_ok": "Bienvenue,",
        "member_login_bad": "ID et telephone ne correspondent pas. Reessayez.",
        "member_inactive": "Votre compte est Inactif. Demandez de l'aide au leader.",
        "member_menu_title": " MENU MEMBRE",
        "member_menu_summary": "1. Voir mon resume de participation",
        "member_menu_history": "2. Voir mon historique de presence",
        "member_menu_language": "3. Changer de langue",
        "member_menu_logout": "4. Deconnexion / Retour",
        "member_menu_exit": "0. Quitter",
        "member_demo": "(Demo: ID=1 tel=0788000001  ou  ID=3 tel=0788000003)",
        "main_menu": " MENU PRINCIPAL",
        "menu_members": "1. Gestion des membres",
        "menu_attendance": "2. Presence (Attendance)",
        "menu_projects": "3. Projets",
        "menu_tools": "4. Inventaire des outils",
        "menu_reports": "5. Rapports",
        "menu_search": "6. Recherche",
        "menu_refresh": "7. Actualiser le tableau de bord",
        "menu_language": "8. Changer de langue",
        "menu_logout": "9. Deconnexion",
        "menu_exit": "0. Quitter",
        "enter_choice": "Entrez le choix: ",
        "invalid_choice": "Choix invalide. Reessayez.",
        "refreshing": "Actualisation du tableau de bord...",
        "logged_out": "Deconnecte.",
        "goodbye": "Au revoir. Merci de servir la communaute avec UmugandaSync.",
        "press_enter": "\nAppuyez sur Entree pour continuer...",
        "empty_input": "Le champ ne peut pas etre vide. Reessayez.",
        "invalid_number": "Entrez un nombre entier valide (0 ou plus).",
        "invalid_range": "Entrez un nombre entre",
        "and": "et",
        "invalid_date": "Date invalide. Exemple: 2026-07-23",
        "date_prompt": " (AAAA-MM-JJ): ",
        "yn_prompt": " (o/n): ",
        "dashboard": "TABLEAU DE BORD - ",
        "total_members": "TOTAL MEMBRES       :",
        "active_members": "MEMBRES ACTIFS      :",
        "today_attendance": "PRESENCE AUJOURD'HUI:",
        "ongoing_projects": "PROJETS EN COURS    :",
        "available_tools": "OUTILS DISPONIBLES  :",
        "low_stock_tools": "STOCK FAIBLE        :",
        "overdue_projects": "PROJETS EN RETARD   :",
        "notifications": "=== NOTIFICATIONS ===",
        "warn_low_stock": "Attention: {n} outil(s) presque epuise(s).",
        "warn_overdue": "Attention: Le projet {name} est en retard.",
        "notice_no_attendance": "Avis: Aucune presence enregistree aujourd'hui.",
        "notice_absents": "Avis: {n} membre(s) absents le {date}.",
        "no_warnings": "Aucune alerte urgente. Les donnees semblent correctes.",
        "member_menu": "GESTION DES MEMBRES",
        "m1": "1. Ajouter un membre",
        "m2": "2. Voir tous les membres",
        "m3": "3. Rechercher un membre",
        "m4": "4. Modifier un membre",
        "m5": "5. Supprimer un membre",
        "m6": "6. Desactiver un membre",
        "m7": "7. Reactiver un membre",
        "m0": "0. Retour au menu principal",
        "attendance_menu": "PRESENCE",
        "a1": "1. Enregistrer la presence",
        "a2": "2. Voir toutes les presences",
        "a3": "3. Voir par date",
        "a4": "4. Voir par membre",
        "a5": "5. Rechercher une presence",
        "a6": "6. Pourcentage de presence d'un membre",
        "a7": "7. Analyses (actifs / faibles / absences)",
        "a8": "8. Enregistrer la presence pour tout le village / tous",
        "a9": "9. Resume de participation d'un membre (tout le temps)",
        "a0": "0. Retour au menu principal",
        "project_menu": "GESTION DES PROJETS",
        "p1": "1. Enregistrer un projet",
        "p2": "2. Voir tous les projets",
        "p3": "3. Voir les projets en cours",
        "p4": "4. Voir les projets termines",
        "p5": "5. Voir les projets en retard",
        "p6": "6. Rechercher des projets",
        "p7": "7. Mettre a jour progres / statut",
        "p8": "8. Marquer comme termine",
        "p9": "9. Supprimer un projet",
        "p0": "0. Retour au menu principal",
        "tools_menu": "INVENTAIRE DES OUTILS",
        "t1": "1. Enregistrer un outil",
        "t2": "2. Voir tous les outils",
        "t3": "3. Modifier un outil",
        "t4": "4. Supprimer un outil",
        "t5": "5. Emprunter un outil",
        "t6": "6. Rendre un outil",
        "t7": "7. Alerte stock faible",
        "t8": "8. Historique des emprunts",
        "t0": "0. Retour au menu principal",
        "reports_menu": "RAPPORTS",
        "r1": "1. Resume communautaire",
        "r2": "2. Rapport des membres",
        "r3": "3. Resume des presences",
        "r4": "4. Membres les plus actifs",
        "r5": "5. Membres a faible presence",
        "r6": "6. Resume des projets",
        "r7": "7. Resume de l'inventaire",
        "r8": "8. Presence par village",
        "r0": "0. Retour au menu principal",
        "search_menu": "RECHERCHE",
        "s1": "1. Chercher un membre (ID / nom / telephone)",
        "s2": "2. Chercher un projet par nom",
        "s3": "3. Chercher un outil par nom",
        "s4": "4. Chercher presence par date",
        "s0": "0. Retour",
        "back": "0. Retour au menu principal",
    },
    "rw": {
        "choose_language_title": "HITAMO URURIMI / CHOISIR LA LANGUE / CHOOSE LANGUAGE",
        "lang_option_en": "1. English",
        "lang_option_fr": "2. Francais",
        "lang_option_rw": "3. Ikinyarwanda",
        "lang_prompt": "Hitamo (1-3): ",
        "lang_invalid": "Wahisemo nabi. Tuzakoresha Icyongereza.",
        "lang_set_en": "Language set to English.",
        "lang_set_fr": "Langue definie: Francais.",
        "lang_set_rw": "Ururimi: Ikinyarwanda.",
        "connecting": "Tugahuza na MySQL...",
        "setup_help": "Ubufasha bwo gutegura:",
        "setup1": "1. Tangira MySQL kuri mudasobwa yawe",
        "setup2": "2. Koresha: mysql -u root < database.sql",
        "setup3": "3. Shyira ijambo ry'ibanga rya MySQL muri config.py",
        "app_title": "   UmugandaSync - Sisitemu yo Gucunga Umuganda",
        "app_subtitle": "   Umuganda wa digitale ku bayobozi b'Umudugudu",
        "please_login": "Injira mu konti kugira ngo ukomeze.",
        "demo_login": "(Gerageza: izina=admin  ijambo=admin123)",
        "username": "Izina ry'ukoresha: ",
        "password": "Ijambo ry'ibanga: ",
        "login_ok": "Winjiye neza. Murakaza neza,",
        "login_bad": "Izina cyangwa ijambo ry'ibanga sibyo.",
        "attempts_left": "Amahirwe asigaye:",
        "too_many_attempts": "Wagerageje kenshi. Sisitemu irafunga.",
        "entry_title": "NI NDE WINJIRA?",
        "entry_admin": "1. Umuyobozi / Admin (sisitemu yose)",
        "entry_member": "2. Umunyamuryango (ukwitabira kwanjye gusa)",
        "entry_exit": "0. Gusohoka",
        "entry_prompt": "Hitamo: ",
        "member_entry_title": "INJIRA NK'UMUNYAMURYANGO",
        "member_entry_help": "Andika numero yawe (Member ID) n'telefone kugira ngo urebe amateka yawe y'Umuganda.",
        "member_id_prompt": "Numero yawe (Member ID): ",
        "member_phone_prompt": "Telefone yawe: ",
        "member_login_ok": "Murakaza neza,",
        "member_login_bad": "Numero n'telefone ntibihura. Ongera ugerageze.",
        "member_inactive": "Konti yawe ntikora (Inactive). Saba umuyobozi ubufasha.",
        "member_menu_title": " MENU Y'UMUNYAMURYANGO",
        "member_menu_summary": "1. Reba incamake y'ukwitabira kwanjye",
        "member_menu_history": "2. Reba amateka yanjye y'ukwitabira",
        "member_menu_language": "3. Hindura ururimi",
        "member_menu_logout": "4. Gusohoka / Subira",
        "member_menu_exit": "0. Gusohoka",
        "member_demo": "(Gerageza: ID=1 telefone=0788000001  cyangwa  ID=3 telefone=0788000003)",
        "main_menu": " MENU NKURU",
        "menu_members": "1. Abanyamuryango",
        "menu_attendance": "2. Kwitabira",
        "menu_projects": "3. Imishinga",
        "menu_tools": "4. Ibikoresho",
        "menu_reports": "5. Raporo",
        "menu_search": "6. Gushakisha",
        "menu_refresh": "7. Kongera ikarita y'amakuru",
        "menu_language": "8. Guhindura ururimi",
        "menu_logout": "9. Gusohoka",
        "menu_exit": "0. Gusohoka / Kuvamo",
        "enter_choice": "Hitamo: ",
        "invalid_choice": "Wahisemo nabi. Ongera ugerageze.",
        "refreshing": "Turimo kuvugurura ikarita...",
        "logged_out": "Wasohotse.",
        "goodbye": "Murabeho. Murakoze gukorera umuryango hamwe na UmugandaSync.",
        "press_enter": "\nKanda Enter kugira ngo ukomeze...",
        "empty_input": "Ntabwo ushobora gusiga ubusa. Ongera ugerageze.",
        "invalid_number": "Andika umubare wuzuye (0 cyangwa hejuru).",
        "invalid_range": "Andika umubare uri hagati ya",
        "and": "na",
        "invalid_date": "Itariki ntabwo ari yo. Urugero: 2026-07-23",
        "date_prompt": " (YYYY-MM-DD): ",
        "yn_prompt": " (y/n): ",
        "dashboard": "IKARITA Y'AMAKURU - ",
        "total_members": "ABANYAMURYANGO BOSE   :",
        "active_members": "BAKORA (Active)       :",
        "today_attendance": "KWITABIRA UYU MUNSI   :",
        "ongoing_projects": "IMISHINGA IRIMO       :",
        "available_tools": "IBIKORESHO BIHARI     :",
        "low_stock_tools": "IBIKORESHO BIKE       :",
        "overdue_projects": "IMISHINGA YAREZE      :",
        "notifications": "=== UBUTUMWA ===",
        "warn_low_stock": "Iburira: ibikoresho {n} biri hafi kurangira.",
        "warn_overdue": "Iburira: Umushinga {name} warengeje igihe.",
        "notice_no_attendance": "Menya: Nta kwitabira kwanditswe uyu munsi.",
        "notice_absents": "Menya: abantu {n} ntibaje ku itariki {date}.",
        "no_warnings": "Nta burira bukomeye. Amakuru asa n'aho ari meza.",
        "member_menu": "ABANYAMURYANGO",
        "m1": "1. Ongeraho umunyamuryango",
        "m2": "2. Reba abanyamuryango bose",
        "m3": "3. Shakisha umunyamuryango",
        "m4": "4. Hindura umunyamuryango",
        "m5": "5. Siba umunyamuryango",
        "m6": "6. Hagarika umunyamuryango",
        "m7": "7. Ongera gukoresha umunyamuryango",
        "m0": "0. Subira ku menu nkuru",
        "attendance_menu": "KWITABIRA",
        "a1": "1. Andika kwitabira",
        "a2": "2. Reba kwitabira kwose",
        "a3": "3. Reba ku itariki",
        "a4": "4. Reba ku munyamuryango",
        "a5": "5. Shakisha kwitabira",
        "a6": "6. Ijanisha ry'ukwitabira",
        "a7": "7. Isesengura (bakora / bake / batuje 3)",
        "a8": "8. Andika kwitabira kw'umudugudu wose / bose",
        "a9": "9. Incamake y'ukwitabira kw'umunyamuryango (igihe cyose)",
        "a0": "0. Subira ku menu nkuru",
        "project_menu": "IMISHINGA",
        "p1": "1. Andika umushinga",
        "p2": "2. Reba imishinga yose",
        "p3": "3. Reba imishinga irimo gukorwa",
        "p4": "4. Reba imishinga yarangiye",
        "p5": "5. Reba imishinga yareze",
        "p6": "6. Shakisha imishinga",
        "p7": "7. Hindura intambwe / uko bihagaze",
        "p8": "8. Shyira ko yarangiye",
        "p9": "9. Siba umushinga",
        "p0": "0. Subira ku menu nkuru",
        "tools_menu": "IBIKORESHO",
        "t1": "1. Andika igikoresho",
        "t2": "2. Reba ibikoresho byose",
        "t3": "3. Hindura igikoresho",
        "t4": "4. Siba igikoresho",
        "t5": "5. Guha / gutiza igikoresho",
        "t6": "6. Gusubiza igikoresho",
        "t7": "7. Iburira ry'ibikoresho bike",
        "t8": "8. Amateka yo gutiza",
        "t0": "0. Subira ku menu nkuru",
        "reports_menu": "RAPORO",
        "r1": "1. Incamake y'umuryango",
        "r2": "2. Raporo y'abanyamuryango",
        "r3": "3. Incamake y'ukwitabira",
        "r4": "4. Abakora cyane",
        "r5": "5. Abantu badafite kwitabira neza",
        "r6": "6. Incamake y'imishinga",
        "r7": "7. Incamake y'ibikoresho",
        "r8": "8. Kwitabira ku mudugudu",
        "r0": "0. Subira ku menu nkuru",
        "search_menu": "GUSHAKISHA",
        "s1": "1. Shakisha umunyamuryango (ID / izina / telefone)",
        "s2": "2. Shakisha umushinga ku izina",
        "s3": "3. Shakisha igikoresho ku izina",
        "s4": "4. Shakisha kwitabira ku itariki",
        "s0": "0. Subira",
        "back": "0. Subira ku menu nkuru",
    },
}


def t(key):
    # get text for current language
    lang = current_language
    if lang in TEXTS:
        if key in TEXTS[lang]:
            return TEXTS[lang][key]
    # if missing, try english
    if key in TEXTS["en"]:
        return TEXTS["en"][key]
    return key


def set_language(code):
    global current_language
    if code == "en" or code == "fr" or code == "rw":
        current_language = code
        return True
    return False


def choose_language():
    # ask user at the beginning
    global current_language
    print()
    print("=" * 56)
    print(t("choose_language_title"))
    print("=" * 56)
    print(t("lang_option_en"))
    print(t("lang_option_fr"))
    print(t("lang_option_rw"))
    choice = input(t("lang_prompt")).strip()

    if choice == "1":
        current_language = "en"
        print(t("lang_set_en"))
    elif choice == "2":
        current_language = "fr"
        print(t("lang_set_fr"))
    elif choice == "3":
        current_language = "rw"
        print(t("lang_set_rw"))
    else:
        current_language = "en"
        print(t("lang_invalid"))
    print()
