import logging
from typing import Optional

logger = logging.getLogger(__name__)

current_language: str = "en"

TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "choose_language_title": "CHOOSE LANGUAGE / HITAMO URURIMI / CHOISIR LA LANGUE",
        "lang_option_en": "1. English",
        "lang_option_fr": "2. Francais",
        "lang_option_rw": "3. Ikinyarwanda",
        "lang_prompt": "Enter choice (1-3): ",
        "lang_invalid": "Invalid choice. Using English.",
        "lang_set_en": "Language set to English.",
        "lang_set_fr": "Langue definie: Francais.",
        "lang_set_rw": "Ururimi: Ikinyarwanda.",
        "connecting": "Connecting to MySQL...",
        "setup_help": "Setup help:",
        "setup1": "1. Start MySQL on your computer",
        "setup2": "2. Run: mysql -u root < database.sql",
        "setup3": "3. Put your MySQL password in config.py if needed",
        "app_title": "   UmugandaSync - Community Work Management System",
        "app_subtitle": "   Digital Umuganda for Village / Umudugudu Leaders",
        "please_login": "Please log in to continue.",
        "demo_login": "(Demo: username=admin  password=admin123)",
        "username": "Username: ",
        "password": "Password: ",
        "login_ok": "Login successful. Welcome,",
        "login_bad": "Invalid username or password.",
        "attempts_left": "Attempts left:",
        "too_many_attempts": "Too many failed attempts. Exiting.",
        "entry_title": "WHO IS ENTERING?",
        "entry_admin": "1. Village Leader / Admin (full system)",
        "entry_member": "2. Community Member (my participation only)",
        "entry_exit": "0. Exit",
        "entry_prompt": "Enter choice: ",
        "member_entry_title": "MEMBER ACCESS",
        "member_entry_help": "Enter your Member ID and phone to view your Umuganda record.",
        "member_id_prompt": "Your Member ID: ",
        "member_phone_prompt": "Your phone number: ",
        "member_login_ok": "Welcome,",
        "member_login_bad": "Member ID and phone do not match. Try again.",
        "member_inactive": "Your account is Inactive. Ask the Village Leader for help.",
        "member_menu_title": " MEMBER MENU",
        "member_menu_summary": "1. View my participation summary",
        "member_menu_history": "2. View my attendance history",
        "member_menu_language": "3. Change language",
        "member_menu_logout": "4. Logout / Back to entry",
        "member_menu_exit": "0. Exit",
        "member_demo": "(Demo tip: ID=1 phone=0788000001  or  ID=3 phone=0788000003)",
        "main_menu": " MAIN MENU",
        "menu_members": "1. Member Management",
        "menu_attendance": "2. Attendance",
        "menu_projects": "3. Projects",
        "menu_tools": "4. Tool Inventory",
        "menu_reports": "5. Reports",
        "menu_search": "6. Universal Search",
        "menu_refresh": "7. Refresh Dashboard",
        "menu_language": "8. Change Language",
        "menu_logout": "9. Logout",
        "menu_exit": "0. Exit",
        "menu_reports_sub": "Reports",
        "menu_csv_export": "CSV Export",
        "enter_choice": "Enter choice: ",
        "invalid_choice": "Invalid choice. Please try again.",
        "refreshing": "Refreshing dashboard...",
        "logged_out": "Logged out.",
        "goodbye": "Goodbye. Thank you for serving the community with UmugandaSync.",
        "press_enter": "\nPress Enter to continue...",
        "empty_input": "Input cannot be empty. Try again.",
        "invalid_number": "Please enter a valid whole number (0 or more).",
        "invalid_range": "Please enter a number between",
        "and": "and",
        "invalid_date": "Invalid date. Example: 2026-07-23",
        "date_prompt": " (YYYY-MM-DD): ",
        "yn_prompt": " (y/n): ",
        "dashboard": "DASHBOARD - ",
        "total_members": "TOTAL MEMBERS      :",
        "active_members": "ACTIVE MEMBERS     :",
        "today_attendance": "TODAY'S ATTENDANCE :",
        "ongoing_projects": "ONGOING PROJECTS   :",
        "available_tools": "AVAILABLE TOOLS    :",
        "low_stock_tools": "LOW STOCK TOOLS    :",
        "overdue_projects": "OVERDUE PROJECTS   :",
        "notifications": "=== NOTIFICATIONS ===",
        "warn_low_stock": "Warning: {n} tool(s) are almost finished / low stock.",
        "warn_overdue": "Warning: Project {name} is overdue.",
        "notice_no_attendance": "Notice: No attendance has been recorded today.",
        "notice_absents": "Notice: {n} member(s) were Absent on {date}.",
        "no_warnings": "No urgent warnings. Community records look okay.",
        "member_menu": "MEMBER MANAGEMENT",
        "m1": "1. Add Member",
        "m2": "2. View All Members",
        "m3": "3. Search Member",
        "m4": "4. Update Member",
        "m5": "5. Delete Member",
        "m6": "6. Deactivate Member",
        "m7": "7. Reactivate Member",
        "m0": "0. Back to Main Menu",
        "attendance_menu": "ATTENDANCE",
        "a1": "1. Record Attendance",
        "a2": "2. View All Attendance",
        "a3": "3. View by Date",
        "a4": "4. View by Member",
        "a5": "5. Search Attendance",
        "a6": "6. Attendance Percentage for Member",
        "a7": "7. Analytics (active / poor / missed 3)",
        "a8": "8. Record attendance for whole village / all members",
        "a9": "9. Member participation summary (lifetime)",
        "a0": "0. Back to Main Menu",
        "project_menu": "PROJECT MANAGEMENT",
        "p1": "1. Register Project",
        "p2": "2. View All Projects",
        "p3": "3. View Ongoing Projects",
        "p4": "4. View Completed Projects",
        "p5": "5. View Overdue Projects",
        "p6": "6. Search Projects",
        "p7": "7. Update Project Progress / Status",
        "p8": "8. Mark Project Completed",
        "p9": "9. Delete Project",
        "p0": "0. Back to Main Menu",
        "tools_menu": "TOOL INVENTORY",
        "t1": "1. Register Tool",
        "t2": "2. View All Tools",
        "t3": "3. Update Tool",
        "t4": "4. Delete Tool",
        "t5": "5. Borrow Tool",
        "t6": "6. Return Tool",
        "t7": "7. Low Stock Warning",
        "t8": "8. View Borrow History",
        "t0": "0. Back to Main Menu",
        "reports_menu": "REPORTS",
        "r1": "1. Community Summary",
        "r2": "2. Member Report",
        "r3": "3. Attendance Summary",
        "r4": "4. Most Active Members",
        "r5": "5. Members with Poor Attendance",
        "r6": "6. Project Summary",
        "r7": "7. Inventory Summary",
        "r8": "8. Attendance by Village",
        "r9": "9. Export Community Summary to File",
        "r0": "0. Back to Main Menu",
        "search_menu": "UNIVERSAL SEARCH",
        "s1": "1. Search Member (ID / name / phone)",
        "s2": "2. Search Project by name",
        "s3": "3. Search Tool by name",
        "s4": "4. Search Attendance by date",
        "s0": "0. Back",
        "back": "0. Back to Main Menu",
        "s5": "5. Search by National ID",
        "s5_title": "NATIONAL ID SEARCH",
        "s5_help": "Enter a 16-digit Rwanda National ID to find the member.",
        "s5_prompt": "National ID (16 digits): ",
        "s5_found": "Found",
        "s5_not_found": "No member found with this National ID.",
        "s5_not_found_tip": "Check the ID or register the member first.",
        "searching_id": "Searching for National ID:",
        "record_s": "record{}",
        "nid_empty": "National ID cannot be empty.",
        "nid_length_error": "National ID must be exactly 16 digits.",
        "nid_digit_error": "National ID must contain only digits (0-9).",
        "nid_prefix_error": "Rwanda National ID must start with 1.",
        "search_term_prompt": "Search term: ",
        "project_name_contains": "Project name contains: ",
        "tool_name_contains": "Tool name contains: ",
        "choose_month_tip": "Tip: Choose the Umuganda month to search.",
        "no_results": "No results found.",
        "total": "Total",
        "csv_export_menu": "CSV EXPORT",
        "csv_e1": "1. Export Members",
        "csv_e2": "2. Export Attendance",
        "csv_e3": "3. Export Projects",
        "csv_e4": "4. Export Tools",
        "csv_e5": "5. Export Community Summary",
        "csv_e0": "0. Back",
        "csv_export_members": "EXPORT MEMBERS TO CSV",
        "csv_export_attendance": "EXPORT ATTENDANCE TO CSV",
        "csv_export_projects": "EXPORT PROJECTS TO CSV",
        "csv_export_tools": "EXPORT TOOLS TO CSV",
        "csv_export_summary": "EXPORT COMMUNITY SUMMARY TO CSV",
        "csv_no_data": "No data to export.",
        "csv_exported": "Exported {count} records to: {path}",
        "csv_export_tip": "Open the file with Excel or Google Sheets.",
        "csv_write_error": "Could not write CSV file:",
        "csv_date_filter_prompt": "Filter by date? (y/n): ",
        "csv_date_prompt": "Date",
        "csv_low_stock_note": "Note: {n} tool(s) are low stock in this export.",
        "section_members": "▌ MEMBERS",
        "section_attendance": "▌ ATTENDANCE",
        "section_projects": "▌ PROJECTS",
        "section_tools": "▌ TOOL INVENTORY",
        "section_umuganda": "▌ NEXT UMUGANDA",
        "section_navigation": "▌ QUICK NAVIGATION",
        "inactive_members": "INACTIVE MEMBERS   :",
        "total_attendance_records": "TOTAL RECORDS      :",
        "umuganda_dates": "UMUGANDA DATES     :",
        "completed_projects": "COMPLETED PROJECTS :",
        "pending_projects": "PENDING PROJECTS   :",
        "tool_types": "TOOL TYPES         :",
        "next_umuganda": "NEXT UMUGANDA DATE :",
        "last_saturday_of": "Last Saturday of",
        "nav_hint": "Use menu numbers (1-9) to navigate. 0 = Exit.",
        "notice_no_attendance_month": "No attendance recorded for {month} Umuganda ({date}).",
        "attendance_summary_notice": "Attendance for {date}: {total} recorded, {present} present.",
        "latest_umuganda": "Latest recorded Umuganda: {date}",
        "active_member_count": "{n} active community members.",
        "member": "Member",
        "member_not_found": "Member not found.",
        "village": "Village",
        "status": "Status",
        "member_summary": "MEMBER SUMMARY",
        "no_attendance_recorded": "No attendance has been recorded yet.",
        "no_attendance": "No attendance records found.",
        "total_sessions": "Total sessions",
        "present": "Present",
        "late": "Late",
        "absent": "Absent",
        "excused": "Excused",
        "attendance_rate": "Attendance rate",
        "no_attendance_data": "No attendance data for this member.",
        "member_inactive_attendance": "Cannot record attendance for an inactive member.",
        "attendance_exists_today": "Attendance already recorded for this member today.",
        "attendance_status_prompt": "Choose attendance status:",
        "attendance_recorded": "Attendance recorded successfully.",
        "attendance_record_failed": "Failed to record attendance.",
        "date_prompt_text": "Date",
        "ever_attended": "Members who ever attended:",
        "never_attended_tip": "active member(s) have never attended any Umuganda.",
        "members_3_absences": "Members with 3+ absences",
        "absences_lc": "absences",
        "no_poor_attendance": "No members with 3+ absences.",
        "a8_help": "Record attendance for all active members at once.",
        "continue_question": "Continue?",
        "no_active_members": "No active members found.",
        "default_status_prompt": "Default status for all (1-4, default Present): ",
        "village_recorded": "Attendance recorded for",
        "already_recorded": "already had attendance",
        "project_name_prompt": "Project name: ",
        "project_desc_prompt": "Description (optional): ",
        "project_location_prompt": "Location: ",
        "project_leader_prompt": "Leader Member ID: ",
        "project_start_prompt": "Start date",
        "project_end_prompt": "Expected end date",
        "project_added": "Project registered successfully.",
        "project_add_failed": "Failed to register project.",
        "project_not_found": "Project not found.",
        "current_values": "Current values",
        "due": "Due:",
        "progress_prompt": "New progress percentage",
        "project_updated": "Project updated.",
        "project_update_failed": "Failed to update project.",
        "mark_complete": "Mark as completed",
        "are_you_sure": "Are you sure?",
        "project_completed": "Project marked as completed.",
        "project_complete_failed": "Failed to mark project as completed.",
        "confirm_delete": "You will delete",
        "project_deleted": "Project deleted.",
        "project_delete_failed": "Failed to delete project.",
        "no_projects": "No projects found.",
        "no_leader": "(no leader)",
        "leader": "Leader",
        "project_id_prompt": "Project ID: ",
        "tool_name_prompt": "Tool name: ",
        "tool_category_prompt": "Category: ",
        "tool_total_qty_prompt": "Total quantity: ",
        "tool_avail_qty_prompt": "Available quantity: ",
        "tool_condition_prompt": "Condition (Good / Needs Repair / Broken): ",
        "tool_low_stock_prompt": "Low stock alert limit: ",
        "tool_added": "Tool registered.",
        "tool_add_failed": "Failed to register tool.",
        "tool_id_prompt": "Tool ID: ",
        "tool_not_found": "Tool not found.",
        "tool_updated": "Tool updated.",
        "tool_update_failed": "Failed to update tool.",
        "tool_deleted": "Tool deleted.",
        "tool_delete_failed": "Failed to delete tool.",
        "tool_selected": "Selected tool",
        "tool_available": "Available",
        "member_id_prompt2": "Member ID: ",
        "tool_quantity_prompt": "Quantity to borrow: ",
        "tool_not_enough": "Not enough tools available.",
        "tool_borrowed": "Tool borrowed successfully.",
        "tool_borrow_failed": "Failed to borrow tool.",
        "borrow_id_prompt": "Borrow ID: ",
        "borrow_not_found": "Borrow record not found or already returned.",
        "borrow_info": "Borrow info",
        "borrowed_by": "Borrowed by member",
        "since": "Since",
        "confirm_return": "Confirm return?",
        "tool_returned": "Tool returned.",
        "no_tools": "No tools registered.",
        "no_low_stock": "All tools are well stocked.",
        "tools_low_stock_count": "Tools with low stock",
        "no_borrows": "No borrow history.",
        "not_returned": "Not returned",
        "borrowed": "Borrowed",
        "returned": "Returned",
        "gender_distribution": "GENDER DISTRIBUTION :",
        "recent_activity": "RECENT ACTIVITY     :",
        "project_completion_rate": "COMPLETION RATE     :",
        "search_again": "Search again? (y/n): ",
        "member_details": "Member Details",
        "first_name": "First Name",
        "last_name": "Last Name",
        "national_id": "National ID",
        "phone": "Phone",
        "gender": "Gender",
        "cell_name": "Cell",
        "date_registered": "Registered",
        "attendance_stats": "Attendance Stats",
        "total_events": "Total Events",
        "no_attendance_records": "No attendance records found.",
    },
    "fr": {
        "choose_language_title": "CHOISIR LA LANGUE / HITAMO URURIMI / CHOOSE LANGUAGE",
        "lang_option_en": "1. English",
        "lang_option_fr": "2. Francais",
        "lang_option_rw": "3. Ikinyarwanda",
        "lang_prompt": "Entrez le choix (1-3): ",
        "lang_invalid": "Choix invalide. Anglais utilise.",
        "lang_set_en": "Language set to English.",
        "lang_set_fr": "Langue definie: Francais.",
        "lang_set_rw": "Ururimi: Ikinyarwanda.",
        "connecting": "Connexion a MySQL...",
        "setup_help": "Aide a l'installation:",
        "setup1": "1. Demarrez MySQL sur votre ordinateur",
        "setup2": "2. Executez: mysql -u root < database.sql",
        "setup3": "3. Mettez le mot de passe MySQL dans config.py si besoin",
        "app_title": "   UmugandaSync - Gestion du travail communautaire",
        "app_subtitle": "   Umuganda numerique pour les leaders d'Umudugudu",
        "please_login": "Veuillez vous connecter pour continuer.",
        "demo_login": "(Demo: utilisateur=admin  motdepasse=admin123)",
        "username": "Nom d'utilisateur: ",
        "password": "Mot de passe: ",
        "login_ok": "Connexion reussie. Bienvenue,",
        "login_bad": "Nom d'utilisateur ou mot de passe incorrect.",
        "attempts_left": "Tentatives restantes:",
        "too_many_attempts": "Trop d'echecs. Fermeture.",
        "entry_title": "QUI ENTRE?",
        "entry_admin": "1. Leader / Admin (systeme complet)",
        "entry_member": "2. Membre de la communaute (ma participation seulement)",
        "entry_exit": "0. Quitter",
        "entry_prompt": "Entrez le choix: ",
        "member_entry_title": "ACCES MEMBRE",
        "member_entry_help": "Entrez votre ID membre et telephone pour voir votre dossier Umuganda.",
        "member_id_prompt": "Votre ID membre: ",
        "member_phone_prompt": "Votre numero de telephone: ",
        "member_login_ok": "Bienvenue,",
        "member_login_bad": "ID et telephone ne correspondent pas. Reessayez.",
        "member_inactive": "Votre compte est Inactif. Demandez de l'aide au leader.",
        "member_menu_title": " MENU MEMBRE",
        "member_menu_summary": "1. Voir mon resume de participation",
        "member_menu_history": "2. Voir mon historique de presence",
        "member_menu_language": "3. Changer de langue",
        "member_menu_logout": "4. Deconnexion / Retour",
        "member_menu_exit": "0. Quitter",
        "member_demo": "(Demo: ID=1 tel=0788000001  ou  ID=3 tel=0788000003)",
        "main_menu": " MENU PRINCIPAL",
        "menu_members": "1. Gestion des membres",
        "menu_attendance": "2. Presence (Attendance)",
        "menu_projects": "3. Projets",
        "menu_tools": "4. Inventaire des outils",
        "menu_reports": "5. Rapports",
        "menu_search": "6. Recherche",
        "menu_refresh": "7. Actualiser le tableau de bord",
        "menu_language": "8. Changer de langue",
        "menu_logout": "9. Deconnexion",
        "menu_exit": "0. Quitter",
        "menu_reports_sub": "Rapports",
        "menu_csv_export": "Exportation CSV",
        "enter_choice": "Entrez le choix: ",
        "invalid_choice": "Choix invalide. Reessayez.",
        "refreshing": "Actualisation du tableau de bord...",
        "logged_out": "Deconnecte.",
        "goodbye": "Au revoir. Merci de servir la communaute avec UmugandaSync.",
        "press_enter": "\nAppuyez sur Entree pour continuer...",
        "empty_input": "Le champ ne peut pas etre vide. Reessayez.",
        "invalid_number": "Entrez un nombre entier valide (0 ou plus).",
        "invalid_range": "Entrez un nombre entre",
        "and": "et",
        "invalid_date": "Date invalide. Exemple: 2026-07-23",
        "date_prompt": " (AAAA-MM-JJ): ",
        "yn_prompt": " (o/n): ",
        "dashboard": "TABLEAU DE BORD - ",
        "total_members": "TOTAL MEMBRES       :",
        "active_members": "MEMBRES ACTIFS      :",
        "today_attendance": "PRESENCE AUJOURD'HUI:",
        "ongoing_projects": "PROJETS EN COURS    :",
        "available_tools": "OUTILS DISPONIBLES  :",
        "low_stock_tools": "STOCK FAIBLE        :",
        "overdue_projects": "PROJETS EN RETARD   :",
        "notifications": "=== NOTIFICATIONS ===",
        "warn_low_stock": "Attention: {n} outil(s) presque epuise(s).",
        "warn_overdue": "Attention: Le projet {name} est en retard.",
        "notice_no_attendance": "Avis: Aucune presence enregistree aujourd'hui.",
        "notice_absents": "Avis: {n} membre(s) absents le {date}.",
        "no_warnings": "Aucune alerte urgente. Les donnees semblent correctes.",
        "member_menu": "GESTION DES MEMBRES",
        "m1": "1. Ajouter un membre",
        "m2": "2. Voir tous les membres",
        "m3": "3. Rechercher un membre",
        "m4": "4. Modifier un membre",
        "m5": "5. Supprimer un membre",
        "m6": "6. Desactiver un membre",
        "m7": "7. Reactiver un membre",
        "m0": "0. Retour au menu principal",
        "attendance_menu": "PRESENCE",
        "a1": "1. Enregistrer la presence",
        "a2": "2. Voir toutes les presences",
        "a3": "3. Voir par date",
        "a4": "4. Voir par membre",
        "a5": "5. Rechercher une presence",
        "a6": "6. Pourcentage de presence d'un membre",
        "a7": "7. Analyses (actifs / faibles / absences)",
        "a8": "8. Enregistrer la presence pour tout le village / tous",
        "a9": "9. Resume de participation d'un membre (tout le temps)",
        "a0": "0. Retour au menu principal",
        "project_menu": "GESTION DES PROJETS",
        "p1": "1. Enregistrer un projet",
        "p2": "2. Voir tous les projets",
        "p3": "3. Voir les projets en cours",
        "p4": "4. Voir les projets termines",
        "p5": "5. Voir les projets en retard",
        "p6": "6. Rechercher des projets",
        "p7": "7. Mettre a jour progres / statut",
        "p8": "8. Marquer comme termine",
        "p9": "9. Supprimer un projet",
        "p0": "0. Retour au menu principal",
        "tools_menu": "INVENTAIRE DES OUTILS",
        "t1": "1. Enregistrer un outil",
        "t2": "2. Voir tous les outils",
        "t3": "3. Modifier un outil",
        "t4": "4. Supprimer un outil",
        "t5": "5. Emprunter un outil",
        "t6": "6. Rendre un outil",
        "t7": "7. Alerte stock faible",
        "t8": "8. Historique des emprunts",
        "t0": "0. Retour au menu principal",
        "reports_menu": "RAPPORTS",
        "r1": "1. Resume communautaire",
        "r2": "2. Rapport des membres",
        "r3": "3. Resume des presences",
        "r4": "4. Membres les plus actifs",
        "r5": "5. Membres a faible presence",
        "r6": "6. Resume des projets",
        "r7": "7. Resume de l'inventaire",
        "r8": "8. Presence par village",
        "r9": "9. Exporter le résumé de la communauté",
        "r0": "0. Retour au menu principal",
        "search_menu": "RECHERCHE",
        "s1": "1. Chercher un membre (ID / nom / telephone)",
        "s2": "2. Chercher un projet par nom",
        "s3": "3. Chercher un outil par nom",
        "s4": "4. Chercher presence par date",
        "s0": "0. Retour",
        "back": "0. Retour au menu principal",
        "s5": "5. Rechercher par carte d'identite",
        "s5_title": "RECHERCHE PAR CARTE D'IDENTITE",
        "s5_help": "Entrez un numero d'identite de 16 chiffres.",
        "s5_prompt": "Numero d'identite (16 chiffres): ",
        "s5_found": "Trouve",
        "s5_not_found": "Aucun membre avec ce numero d'identite.",
        "s5_not_found_tip": "Verifiez le numero ou enregistrez le membre d'abord.",
        "searching_id": "Recherche du numero d'identite:",
        "record_s": "enregistrement{}",
        "nid_empty": "Le numero d'identite ne peut pas etre vide.",
        "nid_length_error": "Le numero d'identite doit avoir exactement 16 chiffres.",
        "nid_digit_error": "Le numero d'identite doit contenir uniquement des chiffres (0-9).",
        "nid_prefix_error": "Le numero d'identite rwandais doit commencer par 1.",
        "search_term_prompt": "Terme de recherche: ",
        "project_name_contains": "Nom du projet contient: ",
        "tool_name_contains": "Nom de l'outil contient: ",
        "choose_month_tip": "Astuce: Choisissez le mois d'Umuganda.",
        "no_results": "Aucun resultat.",
        "total": "Total",
        "csv_export_menu": "EXPORTATION CSV",
        "csv_e1": "1. Exporter les membres",
        "csv_e2": "2. Exporter les presences",
        "csv_e3": "3. Exporter les projets",
        "csv_e4": "4. Exporter les outils",
        "csv_e5": "5. Exporter le resume communautaire",
        "csv_e0": "0. Retour",
        "csv_export_members": "EXPORTER LES MEMBRES EN CSV",
        "csv_export_attendance": "EXPORTER LES PRESENCES EN CSV",
        "csv_export_projects": "EXPORTER LES PROJETS EN CSV",
        "csv_export_tools": "EXPORTER LES OUTILS EN CSV",
        "csv_export_summary": "EXPORTER LE RESUME COMMUNAUTAIRE EN CSV",
        "csv_no_data": "Aucune donnee a exporter.",
        "csv_exported": "{count} enregistrements exportes vers: {path}",
        "csv_export_tip": "Ouvrez le fichier avec Excel ou Google Sheets.",
        "csv_write_error": "Impossible d'ecrire le fichier CSV:",
        "csv_date_filter_prompt": "Filtrer par date? (o/n): ",
        "csv_date_prompt": "Date",
        "csv_low_stock_note": "Note: {n} outil(s) en stock faible dans cet export.",
        "section_members": "▌ MEMBRES",
        "section_attendance": "▌ PRESENCES",
        "section_projects": "▌ PROJETS",
        "section_tools": "▌ INVENTAIRE DES OUTILS",
        "section_umuganda": "▌ PROCHAIN UMUGANDA",
        "section_navigation": "▌ NAVIGATION RAPIDE",
        "inactive_members": "MEMBRES INACTIFS    :",
        "total_attendance_records": "TOTAL ENREGISTRES   :",
        "umuganda_dates": "DATES D'UMUGANDA    :",
        "completed_projects": "PROJETS TERMINES    :",
        "pending_projects": "PROJETS EN ATTENTE  :",
        "tool_types": "TYPES D'OUTILS      :",
        "next_umuganda": "PROCHAIN UMUGANDA   :",
        "last_saturday_of": "Dernier samedi de",
        "nav_hint": "Utilisez les numeros (1-9) pour naviguer. 0 = Quitter.",
        "notice_no_attendance_month": "Aucune presence enregistree pour Umuganda de {month} ({date}).",
        "attendance_summary_notice": "Presence pour {date}: {total} enregistres, {present} presents.",
        "latest_umuganda": "Dernier Umuganda enregistre: {date}",
        "active_member_count": "{n} membres actifs.",
        "member": "Membre",
        "member_not_found": "Membre introuvable.",
        "village": "Village",
        "status": "Statut",
        "member_summary": "RESUME DU MEMBRE",
        "no_attendance_recorded": "Aucune presence enregistree.",
        "no_attendance": "Aucun enregistrement de presence.",
        "total_sessions": "Total des sessions",
        "present": "Present",
        "late": "En retard",
        "absent": "Absent",
        "excused": "Excuse",
        "attendance_rate": "Taux de presence",
        "no_attendance_data": "Aucune donnee de presence pour ce membre.",
        "member_inactive_attendance": "Impossible d'enregistrer pour un membre inactif.",
        "attendance_exists_today": "Presence deja enregistree pour ce membre aujourd'hui.",
        "attendance_status_prompt": "Choisir le statut de presence:",
        "attendance_recorded": "Presence enregistree.",
        "attendance_record_failed": "Echec de l'enregistrement.",
        "date_prompt_text": "Date",
        "ever_attended": "Membres ayant participe:",
        "never_attended_tip": "membre(s) actif(s) n'ont jamais participe a un Umuganda.",
        "members_3_absences": "Membres avec 3+ absences",
        "absences_lc": "absences",
        "no_poor_attendance": "Aucun membre avec 3+ absences.",
        "a8_help": "Enregistrer la presence pour tous les membres actifs.",
        "continue_question": "Continuer?",
        "no_active_members": "Aucun membre actif.",
        "default_status_prompt": "Statut par defaut (1-4, defaut Present): ",
        "village_recorded": "Presence enregistree pour",
        "already_recorded": "deja enregistre(s)",
        "project_name_prompt": "Nom du projet: ",
        "project_desc_prompt": "Description (optionnel): ",
        "project_location_prompt": "Lieu: ",
        "project_leader_prompt": "ID du leader: ",
        "project_start_prompt": "Date de debut",
        "project_end_prompt": "Date de fin prevue",
        "project_added": "Projet enregistre.",
        "project_add_failed": "Echec de l'enregistrement.",
        "project_not_found": "Projet introuvable.",
        "current_values": "Valeurs actuelles",
        "due": "Echeance:",
        "progress_prompt": "Nouveau pourcentage",
        "project_updated": "Projet mis a jour.",
        "project_update_failed": "Echec de la mise a jour.",
        "mark_complete": "Marquer comme termine",
        "are_you_sure": "Etes-vous sur?",
        "project_completed": "Projet termine.",
        "project_complete_failed": "Echec.",
        "confirm_delete": "Vous allez supprimer",
        "project_deleted": "Projet supprime.",
        "project_delete_failed": "Echec de la suppression.",
        "no_projects": "Aucun projet.",
        "no_leader": "(pas de leader)",
        "leader": "Leader",
        "project_id_prompt": "ID du projet: ",
        "tool_name_prompt": "Nom de l'outil: ",
        "tool_category_prompt": "Categorie: ",
        "tool_total_qty_prompt": "Quantite totale: ",
        "tool_avail_qty_prompt": "Quantite disponible: ",
        "tool_condition_prompt": "Etat (Good / Needs Repair / Broken): ",
        "tool_low_stock_prompt": "Limite de stock faible: ",
        "tool_added": "Outil enregistre.",
        "tool_add_failed": "Echec de l'enregistrement.",
        "tool_id_prompt": "ID de l'outil: ",
        "tool_not_found": "Outil introuvable.",
        "tool_updated": "Outil mis a jour.",
        "tool_update_failed": "Echec de la mise a jour.",
        "tool_deleted": "Outil supprime.",
        "tool_delete_failed": "Echec de la suppression.",
        "tool_selected": "Outil selectionne",
        "tool_available": "Disponible",
        "member_id_prompt2": "ID du membre: ",
        "tool_quantity_prompt": "Quantite a emprunter: ",
        "tool_not_enough": "Pas assez d'outils disponibles.",
        "tool_borrowed": "Outil emprunte.",
        "tool_borrow_failed": "Echec de l'emprunt.",
        "borrow_id_prompt": "ID de l'emprunt: ",
        "borrow_not_found": "Emprunt introuvable ou deja retourne.",
        "borrow_info": "Info emprunt",
        "borrowed_by": "Emprunte par membre",
        "since": "Depuis",
        "confirm_return": "Confirmer le retour?",
        "tool_returned": "Outil retourne.",
        "no_tools": "Aucun outil.",
        "no_low_stock": "Tous les outils sont bien approvisionnes.",
        "tools_low_stock_count": "Outils en stock faible",
        "no_borrows": "Aucun historique d'emprunt.",
        "not_returned": "Non retourne",
        "borrowed": "Emprunte",
        "returned": "Retourne",
        "gender_distribution": "REPARTITION PAR GENRE:",
        "recent_activity": "ACTIVITE RECENTE    :",
        "project_completion_rate": "TAUX D'ACHEVEMENT   :",
        "search_again": "Chercher encore? (o/n): ",
        "member_details": "Details du membre",
        "first_name": "Prenom",
        "last_name": "Nom",
        "national_id": "Carte d'identite",
        "phone": "Telephone",
        "gender": "Genre",
        "cell_name": "Cellule",
        "date_registered": "Enregistre le",
        "attendance_stats": "Statistiques de presence",
        "total_events": "Evenements",
        "no_attendance_records": "Aucun enregistrement de presence.",
    },
    "rw": {
        "choose_language_title": "HITAMO URURIMI / CHOISIR LA LANGUE / CHOOSE LANGUAGE",
        "lang_option_en": "1. English",
        "lang_option_fr": "2. Francais",
        "lang_option_rw": "3. Ikinyarwanda",
        "lang_prompt": "Hitamo (1-3): ",
        "lang_invalid": "Wahisemo nabi. Tuzakoresha Icyongereza.",
        "lang_set_en": "Language set to English.",
        "lang_set_fr": "Langue definie: Francais.",
        "lang_set_rw": "Ururimi: Ikinyarwanda.",
        "connecting": "Tugahuza na MySQL...",
        "setup_help": "Ubufasha bwo gutegura:",
        "setup1": "1. Tangiza MySQL kuri mudasobwa yawe",
        "setup2": "2. Koresha: mysql -u root < database.sql",
        "setup3": "3. Shyira ijambo ry'ibanga rya MySQL muri config.py",
        "app_title": "   UmugandaSync - Porogaramu yo Gucunga Umuganda",
        "app_subtitle": "   Gucunga Umuganda mu buryo bwa digitali ku bayobozi b'Imidugudu",
        "please_login": "Injira kugira ngo ukomeze.",
        "demo_login": "(Gerageza: izina: admin, ijambo ry'ibanga: admin123)",
        "username": "Izina ry'ukoresha: ",
        "password": "Ijambo ry'ibanga: ",
        "login_ok": "Winjiye neza. Murakaza neza,",
        "login_bad": "Izina cyangwa ijambo ry'ibanga sibyo.",
        "attempts_left": "Amahirwe asigaye:",
        "too_many_attempts": "Wagerageje incuro nyinshi. Porogaramu irafunga.",
        "entry_title": "NI NDE WINJIRA?",
        "entry_admin": "1. Umuyobozi (sisitemu yose)",
        "entry_member": "2. Umunyamuryango (ukwitabira kwe gusa)",
        "entry_exit": "0. Gusohoka",
        "entry_prompt": "Hitamo: ",
        "member_entry_title": "INJIRA NK'UMUNYAMURYANGO",
        "member_entry_help": "Andika numero yawe (Member ID) na telefone yawe kugira ngo urebe amateka yawe y'Umuganda.",
        "member_id_prompt": "Numero yawe (Member ID): ",
        "member_phone_prompt": "Telefoni yawe: ",
        "member_login_ok": "Murakaza neza,",
        "member_login_bad": "Member ID na telefoni ntibihuza. Ongera ugerageze.",
        "member_inactive": "Konti yawe ntabwo ikora. Saba umuyobozi ubufasha.",
        "member_menu_title": " MENU Y'UMUNYAMURYANGO",
        "member_menu_summary": "1. Reba incamake y'ukwitabira kwanjye",
        "member_menu_history": "2. Reba amateka yanjye y'ukwitabira",
        "member_menu_language": "3. Hindura ururimi",
        "member_menu_logout": "4. Gusohoka / Subira",
        "member_menu_exit": "0. Gusohoka",
        "member_demo": "(Gerageza: ID: 1, Telefoni: 0788000001 cyangwa ID: 3, Telefoni: 0788000003)",
        "main_menu": " MENU NYAMUKURU",
        "menu_members": "1. Abanyamuryango",
        "menu_attendance": "2. Ukwitabira",
        "menu_projects": "3. Imishinga",
        "menu_tools": "4. Ibikoresho",
        "menu_reports": "5. Raporo",
        "menu_search": "6. Gushakisha",
        "menu_refresh": "7. Kongera ikarita y'amakuru",
        "menu_language": "8. Guhindura ururimi",
        "menu_logout": "9. Gusohoka",
        "menu_exit": "0. Gusohoka",
        "menu_reports_sub": "Raporo",
        "menu_csv_export": "Kohereza CSV",
        "enter_choice": "Hitamo: ",
        "invalid_choice": "Wahisemo nabi. Ongera ugerageze.",
        "refreshing": "Turimo kuvugurura ikarita...",
        "logged_out": "Wasohotse.",
        "goodbye": "Murabeho. Murakoze gukorera umuryango muri UmugandaSync.",
        "press_enter": "\nKanda Enter kugira ngo ukomeze...",
        "empty_input": "Ntugire ubusa. Ongera ugerageze.",
        "invalid_number": "Andika umubare wuzuye (0 cyangwa hejuru).",
        "invalid_range": "Andika umubare uri hagati ya",
        "and": "na",
        "invalid_date": "Itariki ntabwo ari yo. Urugero: 2026-07-23",
        "date_prompt": " (YYYY-MM-DD): ",
        "yn_prompt": " (y/n): ",
        "dashboard": "IKARITA Y'AMAKURU - ",
        "total_members": "ABANYAMURYANGO BOSE   :",
        "active_members": "BAKORA               :",
        "today_attendance": "ABITABIRAYE UYU MUNSI :",
        "ongoing_projects": "IMISHINGA IRIMO       :",
        "available_tools": "IBIKORESHO BIHARI     :",
        "low_stock_tools": "IBIKORESHO BIRI MU BUKE:",
        "overdue_projects": "IMISHINGA YARENZE IGIHE:",
        "notifications": "=== UBUTUMWA ===",
        "warn_low_stock": "Iburira: ibikoresho {n} bisigaye bike.",
        "warn_overdue": "Iburira: Umushinga {name} warenze igihe.",
        "notice_no_attendance": "Menya: Nta kwitabira kwanditswe uyu munsi.",
        "notice_absents": "Menya: abantu {n} nta baje ku itariki {date}.",
        "no_warnings": "Nta burira bukomeye. Amakuru asa nk'aho ari meza.",
        "member_menu": "GUCUNGA ABANYAMURYANGO",
        "m1": "1. Ongeraho umunyamuryango",
        "m2": "2. Reba abanyamuryango bose",
        "m3": "3. Shakisha umunyamuryango",
        "m4": "4. Hindura umunyamuryango",
        "m5": "5. Siba umunyamuryango",
        "m6": "6. Hagarika umunyamuryango",
        "m7": "7. Ongera gukoresha umunyamuryango",
        "m0": "0. Subira ku menu nyamukuru",
        "attendance_menu": "UKWITABIRA",
        "a1": "1. Andika ukwitabira",
        "a2": "2. Reba ukwitabira kwose",
        "a3": "3. Reba ukwitabira ku itariki",
        "a4": "4. Reba ukwitabira ku munyamuryango",
        "a5": "5. Shakisha ukwitabira",
        "a6": "6. Ijanisha ry'ukwitabira ku munyamuryango",
        "a7": "7. Isesengura (bakora cyane / batuje / baratannye)",
        "a8": "8. Andika ukwitabira ku mudugudu wose cyangwa bose",
        "a9": "9. Incamake y'ukwitabira kw'umunyamuryango (igihe cyose)",
        "a0": "0. Subira ku menu nyamukuru",
        "project_menu": "GUCUNGA IMISHINGA",
        "p1": "1. Andika umushinga",
        "p2": "2. Reba imishinga yose",
        "p3": "3. Reba imishinga irimo gukorwa",
        "p4": "4. Reba imishinga yarangiye",
        "p5": "5. Reba imishinga yarenze igihe",
        "p6": "6. Shakisha imishinga",
        "p7": "7. Hindura intambwe cyangwa uko bihagaze",
        "p8": "8. Shyira ko umushinga warangiye",
        "p9": "9. Siba umushinga",
        "p0": "0. Subira ku menu nyamukuru",
        "tools_menu": "GUCUNGA IBIKORESHO",
        "t1": "1. Andika igikoresho",
        "t2": "2. Reba ibikoresho byose",
        "t3": "3. Hindura igikoresho",
        "t4": "4. Siba igikoresho",
        "t5": "5. Gutiza igikoresho",
        "t6": "6. Gusubiza igikoresho",
        "t7": "7. Iburira ry'ibikoresho bike",
        "t8": "8. Amateka yo gutiza",
        "t0": "0. Subira ku menu nyamukuru",
        "reports_menu": "RAPORO",
        "r1": "1. Incamake y'umuryango",
        "r2": "2. Raporo y'abanyamuryango",
        "r3": "3. Incamake y'ukwitabira",
        "r4": "4. Abakora cyane mu kwitabira",
        "r5": "5. Abatitabira neza (gukendera kwinshi)",
        "r6": "6. Incamake y'imishinga",
        "r7": "7. Incamake y'ibikoresho",
        "r8": "8. Ukwitabira ku mudugudu",
        "r9": "9. Kohereza incamake y'abaturage mu nyandiko",
        "r0": "0. Subira ku menu nyamukuru",
        "search_menu": "GUSHAKISHA",
        "s1": "1. Shakisha umunyamuryango (ID / izina / telefoni)",
        "s2": "2. Shakisha umushinga ku izina",
        "s3": "3. Shakisha igikoresho ku izina",
        "s4": "4. Shakisha ukwitabira ku itariki",
        "s0": "0. Subira",
        "back": "0. Subira ku menu nyamukuru",
        "s5": "5. Gushakisha ku ndangamuntu",
        "s5_title": "GUSHAKISHA KU NDANGAMUNTU",
        "s5_help": "Andika nimero y'indangamuntu y'imibare 16.",
        "s5_prompt": "Indangamuntu (imibare 16): ",
        "s5_found": "Yabonetse",
        "s5_not_found": "Nta munyamuryango ufite iyi ndangamuntu.",
        "s5_not_found_tip": "Suzuma nimero cyangwa wandikishe umunyamuryango mbere.",
        "searching_id": "Turimo gushakisha indangamuntu:",
        "record_s": "inyandiko{}",
        "nid_empty": "Indangamuntu ntishobora kuba ubusa.",
        "nid_length_error": "Indangamuntu igomba kuba imibare 16 gusa.",
        "nid_digit_error": "Indangamuntu igomba kuba imibare gusa (0-9).",
        "nid_prefix_error": "Indangamuntu y'u Rwanda igomba gutangira na 1.",
        "search_term_prompt": "Ijambo ryo gushakisha: ",
        "project_name_contains": "Izina ry'umushinga ririmo: ",
        "tool_name_contains": "Izina ry'igikoresho ririmo: ",
        "choose_month_tip": "Icyitonderwa: Hitamo ukwezi kw'Umuganda.",
        "no_results": "Nta bisubizo.",
        "total": "Igiteranyo",
        "csv_export_menu": "KOHEREZA CSV",
        "csv_e1": "1. Kohereza abanyamuryango",
        "csv_e2": "2. Kohereza ukwitabira",
        "csv_e3": "3. Kohereza imishinga",
        "csv_e4": "4. Kohereza ibikoresho",
        "csv_e5": "5. Kohereza incamake y'umuryango",
        "csv_e0": "0. Subira",
        "csv_export_members": "KOHEREZA ABANYAMURYANGO MURI CSV",
        "csv_export_attendance": "KOHEREZA UKWITABIRA MURI CSV",
        "csv_export_projects": "KOHEREZA IMISHINGA MURI CSV",
        "csv_export_tools": "KOHEREZA IBIKORESHO MURI CSV",
        "csv_export_summary": "KOHEREZA INCAMAKE Y'UMURYANGO MURI CSV",
        "csv_no_data": "Nta makuru yo kohereza.",
        "csv_exported": "Inyandiko {count} zoherejwe: {path}",
        "csv_export_tip": "Fungura dosiye muri Excel cyangwa Google Sheets.",
        "csv_write_error": "Ntibyashobotse kwandika dosiye ya CSV:",
        "csv_date_filter_prompt": "Gushakisha ku itariki? (y/n): ",
        "csv_date_prompt": "Itariki",
        "csv_low_stock_note": "Icyitonderwa: Ibikoresho {n} biri mu buke muri iyi raporo.",
        "section_members": "▌ ABANYAMURYANGO",
        "section_attendance": "▌ UKWITABIRA",
        "section_projects": "▌ IMISHINGA",
        "section_tools": "▌ IBIKORESHO",
        "section_umuganda": "▌ UMUGANDA UTAHA",
        "section_navigation": "▌ INZIRA YIHUSE",
        "inactive_members": "BADAKORA             :",
        "total_attendance_records": "INYANDIKO ZOSE        :",
        "umuganda_dates": "AMATARIKI Y'UMUGANDA  :",
        "completed_projects": "IMISHINGA YARANGIYE   :",
        "pending_projects": "IMISHINGA ITEGEREJE   :",
        "tool_types": "UBWOKO BW'IBIKORESHO  :",
        "next_umuganda": "ITARIKI Y'UMUGANDA    :",
        "last_saturday_of": "Ku wa Gatandatu wa nyuma wa",
        "nav_hint": "Koresha nimero (1-9) kugira ngo ujye ahandi. 0 = Gusohoka.",
        "notice_no_attendance_month": "Nta kwitabira kwanditswe ku kwezi kwa {month} ({date}).",
        "attendance_summary_notice": "Ukwitabira ku itariki {date}: {total} banditswe, {present} baje.",
        "latest_umuganda": "Umuganda wa nyuma wanditswe: {date}",
        "active_member_count": "Abanyamuryango {n} bakora.",
        "member": "Umunyamuryango",
        "member_not_found": "Umunyamuryango ntaboneka.",
        "village": "Umudugudu",
        "status": "Imiterere",
        "member_summary": "INCAMAKE Y'UMUNYAMURYANGO",
        "no_attendance_recorded": "Nta kwitabira kwanditswe.",
        "no_attendance": "Nta nyandiko y'ukwitabira.",
        "total_sessions": "Inyandiko zose",
        "present": "Yabayeho",
        "late": "Yatinze",
        "absent": "Ntiyaje",
        "excused": "Yisobanuye",
        "attendance_rate": "Igipimo cy'ukwitabira",
        "no_attendance_data": "Nta makuru y'ukwitabira ku munyamuryango.",
        "member_inactive_attendance": "Ntushobora kwandika ukwitabira ku munyamuryango udakora.",
        "attendance_exists_today": "Ukwitabira byamaze kwandikwa uyu munsi.",
        "attendance_status_prompt": "Hitamo imiterere y'ukwitabira:",
        "attendance_recorded": "Ukwitabira kwanditswe neza.",
        "attendance_record_failed": "Kwandika ukwitabira byanze.",
        "date_prompt_text": "Itariki",
        "ever_attended": "Abitabiriye:",
        "never_attended_tip": "umunyamuryango ukora ntiyigeze yitabira Umuganda.",
        "members_3_absences": "Abafite gukendera 3+",
        "absences_lc": "gukendera",
        "no_poor_attendance": "Nta muntu ufite gukendera 3+.",
        "a8_help": "Andika ukwitabira kw'abanyamuryango bose bakora.",
        "continue_question": "Gukomeza?",
        "no_active_members": "Nta munyamuryango ukora.",
        "default_status_prompt": "Imiterere isanzwe (1-4, isanzwe Present): ",
        "village_recorded": "Ukwitabira kwanditswe",
        "already_recorded": "basanzwe banditswe",
        "project_name_prompt": "Izina ry'umushinga: ",
        "project_desc_prompt": "Ibisobanuro (bishobora kubura): ",
        "project_location_prompt": "Aho uherereye: ",
        "project_leader_prompt": "ID y'umuyobozi w'umushinga: ",
        "project_start_prompt": "Itariki yo gutangirira",
        "project_end_prompt": "Itariki y'iherezo riteganijwe",
        "project_added": "Umushinga wanditswe neza.",
        "project_add_failed": "Byanze kwandika umushinga.",
        "project_not_found": "Umushinga ntuboneka.",
        "current_values": "Ibiriho ubu",
        "due": "Igihe:",
        "progress_prompt": "Igipimo gishya cy'iterambere",
        "project_updated": "Umushinga wavuguruwe.",
        "project_update_failed": "Byanze kuvugurura umushinga.",
        "mark_complete": "Shyira ko warangiye",
        "are_you_sure": "Uzi neza?",
        "project_completed": "Umushinga warangiye.",
        "project_complete_failed": "Byanze gushyira ko umushinga warangiye.",
        "confirm_delete": "Ugiye gusiba",
        "project_deleted": "Umushinga wasibwe.",
        "project_delete_failed": "Byanze gusiba umushinga.",
        "no_projects": "Nta mishinga.",
        "no_leader": "(nta muyobozi)",
        "leader": "Umuyobozi",
        "project_id_prompt": "ID y'umushinga: ",
        "tool_name_prompt": "Izina ry'igikoresho: ",
        "tool_category_prompt": "Icyiciro: ",
        "tool_total_qty_prompt": "Umubare wose: ",
        "tool_avail_qty_prompt": "Umubare uhari: ",
        "tool_condition_prompt": "Imiterere (Good / Needs Repair / Broken): ",
        "tool_low_stock_prompt": "Urugero rw'ubuke: ",
        "tool_added": "Igikoresho cyanditswe neza.",
        "tool_add_failed": "Byanze kwandika igikoresho.",
        "tool_id_prompt": "ID y'igikoresho: ",
        "tool_not_found": "Igikoresho ntikiboneka.",
        "tool_updated": "Igikoresho cyavuguruwe.",
        "tool_update_failed": "Byanze kuvugurura igikoresho.",
        "tool_deleted": "Igikoresho cyasibwe.",
        "tool_delete_failed": "Byanze gusiba igikoresho.",
        "tool_selected": "Igikoresho cyahisemo",
        "tool_available": "Gihari",
        "member_id_prompt2": "ID y'umunyamuryango: ",
        "tool_quantity_prompt": "Umubare wo gutiza: ",
        "tool_not_enough": "Ibikoresho ntibihari bihagije.",
        "tool_borrowed": "Igikoresho cyatijwe neza.",
        "tool_borrow_failed": "Byanze gutiza igikoresho.",
        "borrow_id_prompt": "ID yo gutiza: ",
        "borrow_not_found": "Icyo gutiza ntikiboneka cyangwa byamaze gusubizwa.",
        "borrow_info": "Amakuru yo gutiza",
        "borrowed_by": "Cyatijwe n'umunyamuryango",
        "since": "Kuva",
        "confirm_return": "Emeza gusubiza?",
        "tool_returned": "Igikoresho cyasubijwe.",
        "no_tools": "Nta bikoresho.",
        "no_low_stock": "Ibikoresho byose birahagije.",
        "tools_low_stock_count": "Ibikoresho biri mu buke",
        "no_borrows": "Nta mateka yo gutiza.",
        "not_returned": "Ntirasubijwe",
        "borrowed": "Cyatijwe",
        "returned": "Cyasubijwe",
        "gender_distribution": "IGABANYA RY'ITSINA   :",
        "recent_activity": "IBIKORWA BIHERUTSE    :",
        "project_completion_rate": "IGIPIMO CY'UZURA    :",
        "search_again": "Shakisha nanone? (y/n): ",
        "member_details": "Ibisobanuro by'umunyamuryango",
        "first_name": "Izina",
        "last_name": "Umukandara",
        "national_id": "Indangamuntu",
        "phone": "Telefoni",
        "gender": "Igitsina",
        "cell_name": "Akagari",
        "date_registered": "Iyandikishijwe",
        "attendance_stats": "Imibare y'ukwitabira",
        "total_events": "Ibyabaye byose",
        "no_attendance_records": "Nta byanditswe by'ukwitabira.",
    },
}


def t(key: str, fallback: str = "") -> str:
    lang = current_language
    if lang in TEXTS and key in TEXTS[lang]:
        return TEXTS[lang][key]
    if key in TEXTS["en"]:
        return TEXTS["en"][key]
    if fallback:
        return fallback
    logger.warning(f"Missing translation key: '{key}' for language '{lang}'")
    return key


def set_language(code: str) -> bool:
    global current_language
    if code in ("en", "fr", "rw"):
        current_language = code
        logger.info(f"Language set to '{code}'")
        return True
    logger.warning(f"Attempted to set unknown language: '{code}'")
    return False


def choose_language() -> None:
    global current_language
    print()
    print("=" * 56)
    print(t("choose_language_title"))
    print("=" * 56)
    print(t("lang_option_en"))
    print(t("lang_option_fr"))
    print(t("lang_option_rw"))
    choice = input(t("lang_prompt")).strip()

    if choice == "1":
        current_language = "en"
    elif choice == "2":
        current_language = "fr"
    elif choice == "3":
        current_language = "rw"
    else:
        current_language = "en"
        print(t("lang_invalid"))

    print(t(f"lang_set_{current_language}"))
    print()


def add_keys(lang: str, keys: dict[str, str]) -> None:
    if lang not in TEXTS:
        TEXTS[lang] = {}
    TEXTS[lang].update(keys)
    logger.debug(f"Added {len(keys)} keys to language '{lang}'")


def get_available_languages() -> list[str]:
    return list(TEXTS.keys())
